blank_issues_enabled: false
contact_links:
  - name: Security policy
    url: /security
    about: Report security issues
  - name: Support forum
    url: https://forums.unraid.net
    about: For usage questions
