blank_issues_enabled: true
issues:
  - feature_request.yaml
contact_links:
  - name: Security policy
    url: /security
    about: Report security issues
  - name: Support forum
    url: https://forums.unraid.net
    about: For usage questions
